version: "3.8"

services:
  app:
    build: .
    depends_on:
      - mongodb
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    restart: unless-stopped
  mongodb:
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    image: mongo:5.0.2
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    restart: unless-stopped
    volumes:
      - db:/data/db
volumes:
  db:
